### ISSUE TITLE
Add plotting to the history

### ISSUE THREAD

**Issue by bandrzejczak** [bandrzejczak/harmony-search#1]
It would be nice to show the plot of different harmonics through the history and their quality. It could be done only for one and two dimensional problems, so it's a matter of question whether is should be defined inside metaheuristic itself, or whether plotting should be optional and defined inside utils so it could be used after computation (i.e. at the end of squared.r)

**Comment by Thurs997** [comment]
Plotting applied to Ratrigin function only (experiments/rastrigin.r), acutually works only on two-dimensional problems. It'd be easy to expand it or generify, but it's unnecessary right now.
